CREATE DATABASE short_link;

CREATE TABLE auth_user(
	user_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	email VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	name VARCHAR(25) NOT NULL
);

CREATE TABLE link(
	user_id INT REFERENCES auth_user ON DELETE CASCADE,
	link VARCHAR NOT NULL,
	short_link VARCHAR NOT NULL,
	code VARCHAR NOT NULL,
	date_added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	clicks NUMERIC DEFAULT 0
);
